
apiVersion: v1
kind: Namespace
metadata:
  name: student-api

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: student-api
data:
  POSTGRES_DB: "postgres_db"
  POSTGRES_PORT: "5432"

---

apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-secrets
  namespace: student-api
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-cluster
  target:
    name: db-secrets
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_USER
      remoteRef: 
        key: app-secrets
        property: POSTGRES_USER
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: app-secrets
        property: POSTGRES_PASSWORD

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: student-api
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: StatefulSet
metadata: 
  name: postgres
  namespace: student-api
spec:
  serviceName: postgres
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      nodeSelector:
        type: database
      containers:
        - name: postgres
          image: postgres
          envFrom:
            - configMapRef:
                name: db-config
            - secretRef:
                name: db-secrets
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: postgres-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: student-api
spec:
  type: ClusterIP 
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432

    