apiVersion: v1
kind: Namespace
metadata: 
  name: vault 

---

apiVersion: v1
kind: Secret
metadata:
  name: vault-root-token
  namespace: vault
type: Opaque
stringData:
  token: dev-only-token

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  namespace: vault
spec:
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      nodeSelector:
        type: dependent_services
      containers:
        - name: vault
          image: hashicorp/vault:1.20
          args: ["server", "-dev", "-dev-listen-address=0.0.0.0:8200", "-dev-root-token-id=dev-only-token"]
          

---
apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: vault
spec:
  type: ClusterIP
  selector:
    app: vault
  ports:
    - port: 8200
      targetPort: 8200
