apiVersion: v1
kind: Service
metadata:
  name: flask-api
  labels:
    app: flask-api
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodeport }}
  selector:
    app: flask-api
    
