"""enter message

Revision ID: 5f57d2fb4f7a
Revises: 9ea39a735c36
Create Date: 2025-09-11 06:20:53.397721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f57d2fb4f7a'
down_revision = '9ea39a735c36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('department')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department', sa.VARCHAR(length=20), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
