"""drop dept

Revision ID: b4b1b97dbe2d
Revises: 5c71418d5a17
Create Date: 2025-09-24 00:00:41.084821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4b1b97dbe2d'
down_revision = '5c71418d5a17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('dept')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dept', sa.VARCHAR(length=20), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
