"""remove address

Revision ID: e8ec3a630994
Revises: c066dd74d5d5
Create Date: 2025-09-10 14:47:36.635536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8ec3a630994'
down_revision = 'c066dd74d5d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.VARCHAR(length=500), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
