global:
  nodeSelector:
    node-type: dependent_services

controller:
  nodeSelector:
    node-type: dependent_services

repoServer:
  nodeSelector:
    node-type: dependent_services

server:
  nodeSelector:
    node-type: dependent_services
  service:
    type: ClusterIP

applicationSet:
  nodeSelector:
    node-type: dependent_services
