apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-secrets
  namespace: student-api
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-cluster
  target:
    name: db-secrets
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_USER
      remoteRef: 
        key: app-secrets
        property: POSTGRES_USER
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: app-secrets
        property: POSTGRES_PASSWORD
        