apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-secrets
  namespace: student-api
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-cluster
  target:
    name: db-secrets
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef: { key: app-secrets, property: POSTGRES_USER }
    - secretKey: password 
      remoteRef: { key: app-secrets, property: POSTGRES_PASSWORD }
    - secretKey: postgres-password  
      remoteRef: { key: app-secrets, property: POSTGRES_PASSWORD }
    - secretKey: DATABASE_URL
      remoteRef: { key: app-secrets, property: DATABASE_URL }
