
fullnameOverride: postgres

architecture: standalone

# image:
#   registry: docker.io
#   repository: bitnami/postgresql
#   tag: "16"
#   pullPolicy: IfNotPresent


primary:
  nodeSelector:
    node-type: database
  persistence:
    enabled: true
    size: 1Gi
    storageclass: csi-hostpath-sc


auth:
  existingSecret: db-secrets
  username: "User1"
  database: "postgres_db"


service:
  ports:
    postgresql: 5432
