apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-cluster
spec:
  provider:
    vault:
      server: {{ .Values.vaultAddress | quote }}
      path: {{ .Values.path | quote }}
      version: {{ .Values.version | quote }}
      auth:
        tokenSecretRef:
          name: vault-root-token
          key: token
          namespace: vault
