installCRDs: true
nodeSelector: { type: dependent_services }
webhook:
  create: true
  nodeSelector: { type: dependent_services }
certController:
  create: true
  nodeSelector: { type: dependent_services }
